comment:
  layout: "header, diff, components"

coverage:
  status:
    project:
      default:
        target: auto
        base: auto
    patch:
      default:
        target: auto
        base: auto

component_management:
  individual_components:
    - component_id: riverpod_app
      name: Riverpod App
      paths:
        - riverpod_app/**/*
    - component_id: bloc_app
      name: BLoC App
      paths:
        - bloc_app/**/*
    - component_id: common
      name: Common Package
      paths:
        - common/**/*

  default_rules:
    statuses:
      - type: project
        target: auto
        base: auto
      - type: patch
        target: auto
        base: auto
