comment:
  layout: "header, diff, components"
  show_carryforward_flags: true

ignore:
  - "**/app_localizations*.dart"

coverage:
  status:
    project:
      default:
        target: auto
        base: auto
    patch:
      default:
        target: auto
        base: auto

flags:
  riverpod_app:
    paths:
      - riverpod_app/**/*
    carryforward: true
  bloc_app:
    paths:
      - bloc_app/**/*
    carryforward: true
  common:
    paths:
      - common/**/*
    carryforward: true

component_management:
  individual_components:
    - component_id: riverpod_app
      name: Riverpod App
      paths:
        - riverpod_app/**/*
    - component_id: bloc_app
      name: BLoC App
      paths:
        - bloc_app/**/*
    - component_id: common
      name: Common Package
      paths:
        - common/**/*

  default_rules:
    statuses:
      - type: project
        target: auto
        base: auto
      - type: patch
        target: auto
        base: auto
