name: 'Build Flutter Package'
description: 'Sets up, checks, tests, and uploads results for a Flutter package'

inputs:
  working-directory:
    description: 'Working directory of the Flutter package'
    required: true
  codecov-token:
    description: 'Codecov token for uploading results (optional for public repos)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Flutter package
      uses: ./.github/actions/setup-flutter-package
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Check Flutter package
      uses: ./.github/actions/check-flutter-package
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Run tests
      id: tests
      uses: ./.github/actions/run-tests
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Upload test results
      if: ${{ !cancelled() }}
      uses: ./.github/actions/upload-test-results
      with:
        token: ${{ inputs.codecov-token }}
        package-name: ${{ inputs.working-directory }}
        coverage-files: ${{ steps.tests.outputs.coverage-file }}
        test-results-files: ${{ steps.tests.outputs.test-results-file }}
