// Mocks generated by Mockito 5.4.5 from annotations
// in riverpod_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i19;
import 'dart:typed_data' as _i21;

import 'package:common/common.dart' as _i23;
import 'package:dio/src/adapter.dart' as _i6;
import 'package:dio/src/cancel_token.dart' as _i25;
import 'package:dio/src/dio.dart' as _i10;
import 'package:dio/src/dio_exception.dart' as _i30;
import 'package:dio/src/dio_mixin.dart' as _i8;
import 'package:dio/src/headers.dart' as _i17;
import 'package:dio/src/options.dart' as _i5;
import 'package:dio/src/redirect_record.dart' as _i29;
import 'package:dio/src/response.dart' as _i9;
import 'package:dio/src/transformer.dart' as _i7;
import 'package:file/file.dart' as _i2;
import 'package:flutter/widgets.dart' as _i12;
import 'package:flutter_cache_manager/src/cache_managers/base_cache_manager.dart'
    as _i18;
import 'package:flutter_cache_manager/src/result/file_info.dart' as _i3;
import 'package:flutter_cache_manager/src/result/file_response.dart' as _i20;
import 'package:go_router/src/configuration.dart' as _i11;
import 'package:go_router/src/delegate.dart' as _i13;
import 'package:go_router/src/information_provider.dart' as _i14;
import 'package:go_router/src/match.dart' as _i28;
import 'package:go_router/src/parser.dart' as _i15;
import 'package:go_router/src/router.dart' as _i26;
import 'package:go_router/src/state.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i27;
import 'package:riverpod_app/data/repositories/challenges_repository.dart'
    as _i22;
import 'package:riverpod_app/data/repositories/concepts_repository.dart'
    as _i24;
import 'package:riverpod_app/data/services/rest_client.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeFileInfo_1 extends _i1.SmartFake implements _i3.FileInfo {
  _FakeFileInfo_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeRestClient_2 extends _i1.SmartFake implements _i4.RestClient {
  _FakeRestClient_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeBaseOptions_3 extends _i1.SmartFake implements _i5.BaseOptions {
  _FakeBaseOptions_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_4 extends _i1.SmartFake
    implements _i6.HttpClientAdapter {
  _FakeHttpClientAdapter_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTransformer_5 extends _i1.SmartFake implements _i7.Transformer {
  _FakeTransformer_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeInterceptors_6 extends _i1.SmartFake implements _i8.Interceptors {
  _FakeInterceptors_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeResponse_7<T1> extends _i1.SmartFake implements _i9.Response<T1> {
  _FakeResponse_7(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDio_8 extends _i1.SmartFake implements _i10.Dio {
  _FakeDio_8(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeRouteConfiguration_9 extends _i1.SmartFake
    implements _i11.RouteConfiguration {
  _FakeRouteConfiguration_9(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeBackButtonDispatcher_10 extends _i1.SmartFake
    implements _i12.BackButtonDispatcher {
  _FakeBackButtonDispatcher_10(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGoRouterDelegate_11 extends _i1.SmartFake
    implements _i13.GoRouterDelegate {
  _FakeGoRouterDelegate_11(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGoRouteInformationProvider_12 extends _i1.SmartFake
    implements _i14.GoRouteInformationProvider {
  _FakeGoRouteInformationProvider_12(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGoRouteInformationParser_13 extends _i1.SmartFake
    implements _i15.GoRouteInformationParser {
  _FakeGoRouteInformationParser_13(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGoRouterState_14 extends _i1.SmartFake
    implements _i16.GoRouterState {
  _FakeGoRouterState_14(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeRequestOptions_15 extends _i1.SmartFake
    implements _i5.RequestOptions {
  _FakeRequestOptions_15(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeHeaders_16 extends _i1.SmartFake implements _i17.Headers {
  _FakeHeaders_16(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUri_17 extends _i1.SmartFake implements Uri {
  _FakeUri_17(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeInterceptorState_18<T> extends _i1.SmartFake
    implements _i8.InterceptorState<T> {
  _FakeInterceptorState_18(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [BaseCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseCacheManager extends _i1.Mock implements _i18.BaseCacheManager {
  MockBaseCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i2.File> getSingleFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSingleFile,
          [url],
          {#key: key, #headers: headers},
        ),
        returnValue: _i19.Future<_i2.File>.value(
          _FakeFile_0(
            this,
            Invocation.method(
              #getSingleFile,
              [url],
              {#key: key, #headers: headers},
            ),
          ),
        ),
      ) as _i19.Future<_i2.File>);

  @override
  _i19.Stream<_i3.FileInfo> getFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getFile, [url], {#key: key, #headers: headers}),
        returnValue: _i19.Stream<_i3.FileInfo>.empty(),
      ) as _i19.Stream<_i3.FileInfo>);

  @override
  _i19.Stream<_i20.FileResponse> getFileStream(
    String? url, {
    String? key,
    Map<String, String>? headers,
    bool? withProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileStream,
          [url],
          {#key: key, #headers: headers, #withProgress: withProgress},
        ),
        returnValue: _i19.Stream<_i20.FileResponse>.empty(),
      ) as _i19.Stream<_i20.FileResponse>);

  @override
  _i19.Future<_i3.FileInfo> downloadFile(
    String? url, {
    String? key,
    Map<String, String>? authHeaders,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [url],
          {#key: key, #authHeaders: authHeaders, #force: force},
        ),
        returnValue: _i19.Future<_i3.FileInfo>.value(
          _FakeFileInfo_1(
            this,
            Invocation.method(
              #downloadFile,
              [url],
              {#key: key, #authHeaders: authHeaders, #force: force},
            ),
          ),
        ),
      ) as _i19.Future<_i3.FileInfo>);

  @override
  _i19.Future<_i3.FileInfo?> getFileFromCache(
    String? key, {
    bool? ignoreMemCache = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileFromCache,
          [key],
          {#ignoreMemCache: ignoreMemCache},
        ),
        returnValue: _i19.Future<_i3.FileInfo?>.value(),
      ) as _i19.Future<_i3.FileInfo?>);

  @override
  _i19.Future<_i3.FileInfo?> getFileFromMemory(String? key) =>
      (super.noSuchMethod(
        Invocation.method(#getFileFromMemory, [key]),
        returnValue: _i19.Future<_i3.FileInfo?>.value(),
      ) as _i19.Future<_i3.FileInfo?>);

  @override
  _i19.Future<_i2.File> putFile(
    String? url,
    _i21.Uint8List? fileBytes, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = 'file',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putFile,
          [url, fileBytes],
          {
            #key: key,
            #eTag: eTag,
            #maxAge: maxAge,
            #fileExtension: fileExtension,
          },
        ),
        returnValue: _i19.Future<_i2.File>.value(
          _FakeFile_0(
            this,
            Invocation.method(
              #putFile,
              [url, fileBytes],
              {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i2.File>);

  @override
  _i19.Future<_i2.File> putFileStream(
    String? url,
    _i19.Stream<List<int>>? source, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = 'file',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putFileStream,
          [url, source],
          {
            #key: key,
            #eTag: eTag,
            #maxAge: maxAge,
            #fileExtension: fileExtension,
          },
        ),
        returnValue: _i19.Future<_i2.File>.value(
          _FakeFile_0(
            this,
            Invocation.method(
              #putFileStream,
              [url, source],
              {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i2.File>);

  @override
  _i19.Future<void> removeFile(String? key) => (super.noSuchMethod(
        Invocation.method(#removeFile, [key]),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> emptyCache() => (super.noSuchMethod(
        Invocation.method(#emptyCache, []),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);

  @override
  _i19.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(#dispose, []),
        returnValue: _i19.Future<void>.value(),
        returnValueForMissingStub: _i19.Future<void>.value(),
      ) as _i19.Future<void>);
}

/// A class which mocks [ChallengesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChallengesRepository extends _i1.Mock
    implements _i22.ChallengesRepository {
  MockChallengesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RestClient get restClient => (super.noSuchMethod(
        Invocation.getter(#restClient),
        returnValue: _FakeRestClient_2(
          this,
          Invocation.getter(#restClient),
        ),
      ) as _i4.RestClient);

  @override
  _i19.Future<List<_i23.Challenge>> getChallenges() => (super.noSuchMethod(
        Invocation.method(#getChallenges, []),
        returnValue: _i19.Future<List<_i23.Challenge>>.value(
          <_i23.Challenge>[],
        ),
      ) as _i19.Future<List<_i23.Challenge>>);
}

/// A class which mocks [ConceptsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConceptsRepository extends _i1.Mock
    implements _i24.ConceptsRepository {
  MockConceptsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RestClient get restClient => (super.noSuchMethod(
        Invocation.getter(#restClient),
        returnValue: _FakeRestClient_2(
          this,
          Invocation.getter(#restClient),
        ),
      ) as _i4.RestClient);

  @override
  _i19.Future<List<_i23.Concept>> getConcepts() => (super.noSuchMethod(
        Invocation.method(#getConcepts, []),
        returnValue: _i19.Future<List<_i23.Concept>>.value(
          <_i23.Concept>[],
        ),
      ) as _i19.Future<List<_i23.Concept>>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i10.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_3(this, Invocation.getter(#options)),
      ) as _i5.BaseOptions);

  @override
  set options(_i5.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(#options, _options),
        returnValueForMissingStub: null,
      );

  @override
  _i6.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_4(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i6.HttpClientAdapter);

  @override
  set httpClientAdapter(_i6.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_5(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i7.Transformer);

  @override
  set transformer(_i7.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(#transformer, _transformer),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_6(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i8.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(#close, [], {#force: force}),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<_i9.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {#data: data, #options: options, #cancelToken: cancelToken},
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i25.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {#data: data, #options: options, #cancelToken: cancelToken},
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i25.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i5.FileAccessMode? fileAccessMode = _i5.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [urlPath, savePath],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue: _i19.Future<_i9.Response<dynamic>>.value(
          _FakeResponse_7<dynamic>(
            this,
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<dynamic>>);

  @override
  _i19.Future<_i9.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    _i25.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i5.FileAccessMode? fileAccessMode = _i5.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [uri, savePath],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue: _i19.Future<_i9.Response<dynamic>>.value(
          _FakeResponse_7<dynamic>(
            this,
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<dynamic>>);

  @override
  _i19.Future<_i9.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i25.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i25.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i19.Future<_i9.Response<T>> fetch<T>(_i5.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(#fetch, [requestOptions]),
        returnValue: _i19.Future<_i9.Response<T>>.value(
          _FakeResponse_7<T>(
            this,
            Invocation.method(#fetch, [requestOptions]),
          ),
        ),
      ) as _i19.Future<_i9.Response<T>>);

  @override
  _i10.Dio clone({
    _i5.BaseOptions? options,
    _i8.Interceptors? interceptors,
    _i6.HttpClientAdapter? httpClientAdapter,
    _i7.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#clone, [], {
          #options: options,
          #interceptors: interceptors,
          #httpClientAdapter: httpClientAdapter,
          #transformer: transformer,
        }),
        returnValue: _FakeDio_8(
          this,
          Invocation.method(#clone, [], {
            #options: options,
            #interceptors: interceptors,
            #httpClientAdapter: httpClientAdapter,
            #transformer: transformer,
          }),
        ),
      ) as _i10.Dio);
}

/// A class which mocks [GoRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouter extends _i1.Mock implements _i26.GoRouter {
  MockGoRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.RouteConfiguration get configuration => (super.noSuchMethod(
        Invocation.getter(#configuration),
        returnValue: _FakeRouteConfiguration_9(
          this,
          Invocation.getter(#configuration),
        ),
      ) as _i11.RouteConfiguration);

  @override
  set configuration(_i11.RouteConfiguration? _configuration) =>
      super.noSuchMethod(
        Invocation.setter(#configuration, _configuration),
        returnValueForMissingStub: null,
      );

  @override
  _i12.BackButtonDispatcher get backButtonDispatcher => (super.noSuchMethod(
        Invocation.getter(#backButtonDispatcher),
        returnValue: _FakeBackButtonDispatcher_10(
          this,
          Invocation.getter(#backButtonDispatcher),
        ),
      ) as _i12.BackButtonDispatcher);

  @override
  _i13.GoRouterDelegate get routerDelegate => (super.noSuchMethod(
        Invocation.getter(#routerDelegate),
        returnValue: _FakeGoRouterDelegate_11(
          this,
          Invocation.getter(#routerDelegate),
        ),
      ) as _i13.GoRouterDelegate);

  @override
  set routerDelegate(_i13.GoRouterDelegate? _routerDelegate) =>
      super.noSuchMethod(
        Invocation.setter(#routerDelegate, _routerDelegate),
        returnValueForMissingStub: null,
      );

  @override
  _i14.GoRouteInformationProvider get routeInformationProvider =>
      (super.noSuchMethod(
        Invocation.getter(#routeInformationProvider),
        returnValue: _FakeGoRouteInformationProvider_12(
          this,
          Invocation.getter(#routeInformationProvider),
        ),
      ) as _i14.GoRouteInformationProvider);

  @override
  set routeInformationProvider(
    _i14.GoRouteInformationProvider? _routeInformationProvider,
  ) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationProvider, _routeInformationProvider),
        returnValueForMissingStub: null,
      );

  @override
  _i15.GoRouteInformationParser get routeInformationParser =>
      (super.noSuchMethod(
        Invocation.getter(#routeInformationParser),
        returnValue: _FakeGoRouteInformationParser_13(
          this,
          Invocation.getter(#routeInformationParser),
        ),
      ) as _i15.GoRouteInformationParser);

  @override
  set routeInformationParser(
    _i15.GoRouteInformationParser? _routeInformationParser,
  ) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationParser, _routeInformationParser),
        returnValueForMissingStub: null,
      );

  @override
  bool get overridePlatformDefaultLocation => (super.noSuchMethod(
        Invocation.getter(#overridePlatformDefaultLocation),
        returnValue: false,
      ) as bool);

  @override
  _i16.GoRouterState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGoRouterState_14(this, Invocation.getter(#state)),
      ) as _i16.GoRouterState);

  @override
  bool canPop() =>
      (super.noSuchMethod(Invocation.method(#canPop, []), returnValue: false)
          as bool);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    String? fragment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #namedLocation,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #fragment: fragment,
          },
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #namedLocation,
            [name],
            {
              #pathParameters: pathParameters,
              #queryParameters: queryParameters,
              #fragment: fragment,
            },
          ),
        ),
      ) as String);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
        Invocation.method(#go, [location], {#extra: extra}),
        returnValueForMissingStub: null,
      );

  @override
  void restore(_i28.RouteMatchList? matchList) => super.noSuchMethod(
        Invocation.method(#restore, [matchList]),
        returnValueForMissingStub: null,
      );

  @override
  void goNamed(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #goNamed,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #extra: extra,
            #fragment: fragment,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Future<T?> push<T extends Object?>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
        Invocation.method(#push, [location], {#extra: extra}),
        returnValue: _i19.Future<T?>.value(),
      ) as _i19.Future<T?>);

  @override
  _i19.Future<T?> pushNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamed,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #extra: extra,
          },
        ),
        returnValue: _i19.Future<T?>.value(),
      ) as _i19.Future<T?>);

  @override
  _i19.Future<T?> pushReplacement<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#pushReplacement, [location], {#extra: extra}),
        returnValue: _i19.Future<T?>.value(),
      ) as _i19.Future<T?>);

  @override
  _i19.Future<T?> pushReplacementNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushReplacementNamed,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #extra: extra,
          },
        ),
        returnValue: _i19.Future<T?>.value(),
      ) as _i19.Future<T?>);

  @override
  _i19.Future<T?> replace<T>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
        Invocation.method(#replace, [location], {#extra: extra}),
        returnValue: _i19.Future<T?>.value(),
      ) as _i19.Future<T?>);

  @override
  _i19.Future<T?> replaceNamed<T>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceNamed,
          [name],
          {
            #pathParameters: pathParameters,
            #queryParameters: queryParameters,
            #extra: extra,
          },
        ),
        returnValue: _i19.Future<T?>.value(),
      ) as _i19.Future<T?>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(#pop, [result]),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(#refresh, []),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(#dispose, []),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Response].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponse<T> extends _i1.Mock implements _i9.Response<T> {
  MockResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set data(T? _data) => super.noSuchMethod(
        Invocation.setter(#data, _data),
        returnValueForMissingStub: null,
      );

  @override
  _i5.RequestOptions get requestOptions => (super.noSuchMethod(
        Invocation.getter(#requestOptions),
        returnValue: _FakeRequestOptions_15(
          this,
          Invocation.getter(#requestOptions),
        ),
      ) as _i5.RequestOptions);

  @override
  set requestOptions(_i5.RequestOptions? _requestOptions) => super.noSuchMethod(
        Invocation.setter(#requestOptions, _requestOptions),
        returnValueForMissingStub: null,
      );

  @override
  set statusCode(int? _statusCode) => super.noSuchMethod(
        Invocation.setter(#statusCode, _statusCode),
        returnValueForMissingStub: null,
      );

  @override
  set statusMessage(String? _statusMessage) => super.noSuchMethod(
        Invocation.setter(#statusMessage, _statusMessage),
        returnValueForMissingStub: null,
      );

  @override
  _i17.Headers get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: _FakeHeaders_16(this, Invocation.getter(#headers)),
      ) as _i17.Headers);

  @override
  set headers(_i17.Headers? _headers) => super.noSuchMethod(
        Invocation.setter(#headers, _headers),
        returnValueForMissingStub: null,
      );

  @override
  bool get isRedirect =>
      (super.noSuchMethod(Invocation.getter(#isRedirect), returnValue: false)
          as bool);

  @override
  set isRedirect(bool? _isRedirect) => super.noSuchMethod(
        Invocation.setter(#isRedirect, _isRedirect),
        returnValueForMissingStub: null,
      );

  @override
  List<_i29.RedirectRecord> get redirects => (super.noSuchMethod(
        Invocation.getter(#redirects),
        returnValue: <_i29.RedirectRecord>[],
      ) as List<_i29.RedirectRecord>);

  @override
  set redirects(List<_i29.RedirectRecord>? _redirects) => super.noSuchMethod(
        Invocation.setter(#redirects, _redirects),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> get extra => (super.noSuchMethod(
        Invocation.getter(#extra),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  set extra(Map<String, dynamic>? _extra) => super.noSuchMethod(
        Invocation.setter(#extra, _extra),
        returnValueForMissingStub: null,
      );

  @override
  Uri get realUri => (super.noSuchMethod(
        Invocation.getter(#realUri),
        returnValue: _FakeUri_17(this, Invocation.getter(#realUri)),
      ) as Uri);
}

/// A class which mocks [ResponseInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponseInterceptorHandler extends _i1.Mock
    implements _i8.ResponseInterceptorHandler {
  MockResponseInterceptorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i8.InterceptorState<dynamic>> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i19.Future<_i8.InterceptorState<dynamic>>.value(
          _FakeInterceptorState_18<dynamic>(
            this,
            Invocation.getter(#future),
          ),
        ),
      ) as _i19.Future<_i8.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(Invocation.getter(#isCompleted), returnValue: false)
          as bool);

  @override
  void next(_i9.Response<dynamic>? response) => super.noSuchMethod(
        Invocation.method(#next, [response]),
        returnValueForMissingStub: null,
      );

  @override
  void resolve(_i9.Response<dynamic>? response) => super.noSuchMethod(
        Invocation.method(#resolve, [response]),
        returnValueForMissingStub: null,
      );

  @override
  void reject(
    _i30.DioException? error, [
    bool? callFollowingErrorInterceptor = false,
  ]) =>
      super.noSuchMethod(
        Invocation.method(#reject, [error, callFollowingErrorInterceptor]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClient extends _i1.Mock implements _i4.RestClient {
  MockRestClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<List<_i23.Concept>> getConcepts() => (super.noSuchMethod(
        Invocation.method(#getConcepts, []),
        returnValue: _i19.Future<List<_i23.Concept>>.value(
          <_i23.Concept>[],
        ),
      ) as _i19.Future<List<_i23.Concept>>);

  @override
  _i19.Future<List<_i23.Challenge>> getChallenges() => (super.noSuchMethod(
        Invocation.method(#getChallenges, []),
        returnValue: _i19.Future<List<_i23.Challenge>>.value(
          <_i23.Challenge>[],
        ),
      ) as _i19.Future<List<_i23.Challenge>>);
}
