name: Common Continuous Integration Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/semantic-pr

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/spell-check
