name: Upload Code Coverage and Test Results to Codecov
description: Uploads code coverage and test results to Codecov

inputs:
  package-name:
    description: 'Flutter app/package name'
    required: true
  coverage-files:
    description: 'Comma separated list of paths to the coverage files'
    required: false
  test-results-files:
    description: 'Comma separated list of paths to the test results files'
    required: false

runs:
  using: 'composite'

  steps:
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ${{ inputs.coverage-files }}
        disable_search: true
        name: ${{ inputs.package-name }}-coverage
        flags: ${{ inputs.package-name }}
        fail_ci_if_error: true
        report_type: coverage

    - name: Upload test results to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ${{ inputs.test-results-files }}
        disable_search: true
        name: ${{ inputs.package-name }}-tests
        flags: ${{ inputs.package-name }}
        fail_ci_if_error: true
        report_type: test_results
